// ─── Plant ────────────────────────────────────────────────────────────────────


export type LightCondition = 'cień' | 'półcień' | 'jasne' | 'pełne słońce'

export interface Plant {
  id?: number
  name: string
  species?: string
  room: string
  notes?: string
  imageBase64?: string
  wateringIntervalDays?: number
  fertilizingIntervalDays?: number
  mistingIntervalDays?: number
  cleaningIntervalDays?: number
  /** Key into PlantTemplate.species — the linked species template */
  templateSpecies?: string
  /** Light exposure of this specific plant (independent of the room) */
  lightCondition?: LightCondition
  createdAt: Date
  archivedAt?: Date
  /** Whether the monthly survey is enabled (undefined = true — enabled by default) */
  surveyEnabled?: boolean
}

/** A plant definitely saved in the database — has an id */
export type StoredPlant = Required<Pick<Plant, 'id'>> & Omit<Plant, 'id'>

/** Data to create a new plant (without fields generated by the database) */
export type NewPlant = Omit<Plant, 'id' | 'createdAt'>

/** Partial plant update (without system fields) */
export type PlantUpdate = Partial<NewPlant>

// ─── CareType ─────────────────────────────────────────────────────────────────

export type CareType = 'watering' | 'fertilizing' | 'misting' | 'pruning' | 'repotting' | 'cleaning' | 'other'

export const CARE_TYPE_LABELS: Record<CareType, string> = {
  watering: 'Podlewanie',
  fertilizing: 'Nawożenie',
  misting: 'Zraszanie',
  pruning: 'Przycinanie',
  repotting: 'Przesadzanie',
  cleaning: 'Czyszczenie',
  other: 'Inne',
}

export const CARE_TYPE_ICONS: Record<CareType, string> = {
  watering: 'mdi-water',
  fertilizing: 'mdi-sprout',
  misting: 'mdi-spray',
  pruning: 'mdi-content-cut',
  repotting: 'mdi-pot-mix',
  cleaning: 'mdi-leaf-circle',
  other: 'mdi-dots-horizontal',
}

export const CARE_TYPE_BG: Record<CareType, string> = {
  watering:    'var(--blue-soft)',
  fertilizing: 'var(--copper-soft)',
  misting:     'var(--mist-soft)',
  pruning:     'var(--warn-soft)',
  repotting:   'var(--brown-soft)',
  cleaning:    'var(--accent-soft)',
  other:       'var(--paper-2)',
}

export const CARE_TYPE_FG: Record<CareType, string> = {
  watering:    'var(--blue)',
  fertilizing: 'var(--copper)',
  misting:     'var(--mist)',
  pruning:     'var(--warn)',
  repotting:   'var(--brown)',
  cleaning:    'var(--accent-deep)',
  other:       'var(--ink-3)',
}

/** Care types that have intervals (overdue days can be calculated) */
export type ScheduledCareType = Extract<CareType, 'watering' | 'fertilizing' | 'misting' | 'cleaning'>

// ─── CareEvent ────────────────────────────────────────────────────────────────

export interface CareEvent {
  id?: number
  plantId: number
  type: CareType
  date: Date
  notes?: string
}

/** An event definitely saved in the database */
export type StoredCareEvent = Required<Pick<CareEvent, 'id'>> & Omit<CareEvent, 'id'>

/** Data to create a new event */
export type NewCareEvent = Omit<CareEvent, 'id'>

// ─── CareStatus ───────────────────────────────────────────────────────────────

/** Care status of a plant for a given type */
export type CareStatus = 'ok' | 'due' | 'overdue' | 'never'

export interface CareStatusInfo {
  status: CareStatus
  /** Date of the last event of this type (undefined = never) */
  lastDate?: Date
  /** Number of days since the last event (undefined = never) */
  daysSinceLast?: number
  /** Number of overdue days (positive = overdue, negative = too early) */
  daysOverdue?: number
}

/** Map of care statuses for all types that have an interval */
export type PlantCareStatuses = Record<ScheduledCareType, CareStatusInfo>

// ─── PlantWateringStatus ──────────────────────────────────────────────────────

/** Watering status of a specific plant */
export interface PlantWateringStatus {
  plant: Plant
  /** Number of days since the last watering (null = never watered) */
  daysSince: number | null
  /** Watering interval in days */
  interval: number
  /** Days past due (negative = before due date, 999 = never watered) */
  overdueDays: number
}

// ─── TaskItem ─────────────────────────────────────────────────────────────────

/** Item in the care task list */
export interface TaskItem {
  plant: Plant
  /** Number of days since the last care of this type (null = never) */
  daysSince: number | null
  /** Days past due (0 = due exactly today) */
  overdue: number
}

// ─── DoneItem ─────────────────────────────────────────────────────────────────

/** An event with its associated plant (for the "done today" list) */
export interface DoneItem {
  event: CareEvent
  plant: Plant | undefined
}

// ─── CustomRoom ───────────────────────────────────────────────────────────────

/** A room added by the user (defaults are hardcoded) */
export interface CustomRoom {
  id?: number
  name: string
}

// ─── PlantSurvey ──────────────────────────────────────────────────────────────

export const SURVEY_CONDITION_LABELS: Record<number, string> = {
  1: 'Krytyczna',
  2: 'Słaba',
  3: 'Przeciętna',
  4: 'Dobra',
  5: 'Świetna',
}

export const SURVEY_CONDITION_COLORS: Record<number, string> = {
  1: 'error',
  2: 'warning',
  3: 'blue-grey-darken-2',
  4: 'success',
  5: 'primary',
}

export const SURVEY_CONDITION_FG: Record<number, string> = {
  1: 'var(--warn)',
  2: 'var(--cond-2)',
  3: 'var(--cond-3)',
  4: 'var(--accent-deep)',
  5: 'var(--cond-5)',
}

export const SURVEY_CONDITION_BG: Record<number, string> = {
  1: 'var(--warn-soft)',
  2: 'var(--cond-2-soft)',
  3: 'var(--cond-3-soft)',
  4: 'var(--accent-soft)',
  5: 'var(--cond-5-soft)',
}

export interface PlantSurvey {
  id?: number
  plantId: number
  date: Date
  /** Plant condition: 1 (critical) – 5 (excellent) */
  condition: 1 | 2 | 3 | 4 | 5
  /** Height from the ground in cm */
  heightCm?: number
  notes?: string
  imageBase64?: string
}

export type StoredPlantSurvey = Required<Pick<PlantSurvey, 'id'>> & Omit<PlantSurvey, 'id'>

// ─── Snooze ───────────────────────────────────────────────────────────────────

export type SnoozedCareType = 'watering' | 'fertilizing' | 'misting' | 'cleaning' | 'survey'

export interface Snooze {
  id?: number
  plantId: number
  careType: SnoozedCareType
  until: Date
}

// ─── AppSettings ─────────────────────────────────────────────────────────────

export interface AppSettings {
  id: 1
  snoozeDays: number
  combineWateringFertilizing: boolean
  isDark: boolean
  themeOverride?: boolean | null
  hiddenRooms?: string[]
  roomOrder?: string[]
  notificationsEnabled?: boolean
}

// ─── RepottingDismissal ───────────────────────────────────────────────────────

export interface RepottingDismissal {
  id?: number
  plantId: number
  /** Year from which the plant reappears on the list (currentYear >= dismissedUntilYear) */
  dismissedUntilYear: number
}

// ─── PlantPhoto ───────────────────────────────────────────────────────────────

export interface PlantPhoto {
  id?: number
  plantId: number
  imageBase64: string
  createdAt: Date
}

export type StoredPlantPhoto = Required<Pick<PlantPhoto, 'id'>> & Omit<PlantPhoto, 'id'>

// ─── ExportData ───────────────────────────────────────────────────────────────

export interface ExportData {
  version: number
  exportedAt: string
  plants: Plant[]
  careEvents: CareEvent[]
  surveys?: PlantSurvey[]
  customRooms?: CustomRoom[]
  settings?: Omit<AppSettings, 'id'>
}

// ─── Theme ────────────────────────────────────────────────────────────────────

export type ThemeMode = 'light' | 'dark'

