import { ref, reactive } from 'vue'
import { db } from '@/db'

// Static species → local URL map (generated by scripts/download-plant-images.mjs)
// Imported dynamically so it doesn't block the bundle if the file doesn't exist yet
let staticImages: Record<string, string> = {}
try {
  const mod = await import('@/data/templateImages')
  staticImages = mod.TEMPLATE_IMAGES ?? {}
} catch {
  // file not generated yet — fallback to Wikipedia
}

const CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000

const ALLOWED_IMAGE_HOSTS = ['upload.wikimedia.org', 'commons.wikimedia.org']

function isSafeImageUrl(url: unknown): url is string {
  if (typeof url !== 'string') return false
  try {
    const { protocol, hostname } = new URL(url)
    return protocol === 'https:' && ALLOWED_IMAGE_HOSTS.some((h) => hostname === h || hostname.endsWith(`.${h}`))
  } catch {
    return false
  }
}

async function fetchFromWikipedia(species: string): Promise<string | null> {
  try {
    const encoded = encodeURIComponent(species)
    const res = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encoded}`)
    if (!res.ok) return null
    const data = await res.json()
    const url = data?.thumbnail?.source
    return isSafeImageUrl(url) ? url : null
  } catch {
    return null
  }
}

async function resolveImage(species: string): Promise<string | null> {
  // 1. Local files (instant, no network request)
  const local = staticImages[species]
  if (local) return local

  // 2. IndexedDB cache (for species outside the static map)
  const cached = await db.templateImageCache.get(species)
  if (cached && Date.now() - cached.fetchedAt < CACHE_TTL_MS) return cached.imageUrl

  // 3. Wikipedia API as fallback
  const url = await fetchFromWikipedia(species)
  await db.templateImageCache.put({ species, imageUrl: url, fetchedAt: Date.now() })
  return url
}

export function useTemplateImage() {
  const imageUrl = ref<string | null>(null)
  const loading = ref(false)

  async function load(species: string) {
    imageUrl.value = null
    loading.value = true
    imageUrl.value = await resolveImage(species)
    loading.value = false
  }

  return { imageUrl, loading, load }
}

export function useTemplateImages() {
  const images = reactive<Record<string, string | null>>({})
  const loading = reactive<Record<string, boolean>>({})

  async function loadMany(speciesList: string[]) {
    const toFetch = speciesList.filter((s) => !(s in images))
    for (const s of toFetch) loading[s] = true
    await Promise.all(
      toFetch.map(async (s) => {
        images[s] = await resolveImage(s)
        loading[s] = false
      }),
    )
  }

  return { images, loading, loadMany }
}
